spring.dotenv.enabled=true

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://Finvision:50omdsg3tU3gBkIG@finvision.sks15eq.mongodb.net/?appName=Finvision}
MONGODB_DATABASE=finvision_db
spring.data.mongodb.database=${MONGODB_DATABASE}

spring.application.name=FinVision
server.port=${PORT:8080}

spring.thymeleaf.cache=false

logging.level.org.springframework.data.mongodb=DEBUG
