spring.dotenv.enabled=true

spring.data.mongodb.uri=${MONGODB_URI}
MONGODB_DATABASE=finvision_db
spring.data.mongodb.database=${MONGODB_DATABASE}

spring.application.name=FinVision
server.port=${PORT:8080}

spring.thymeleaf.cache=false

logging.level.org.springframework.data.mongodb=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
