package com.finvision.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * MongoDB document representing a bill or recurring payment in Finvision.
 *
 * <p>A bill tracks a financial obligation for a user, including its amount
 * (fixed or variable), due date, recurrence frequency, reminder schedule,
 * payment status, and a history of past amounts.</p>
 *
 * <p>Stored in the {@code bills} collection.</p>
 */
@Document(collection = "bills")
public class Bill {

    @Id
    private String id;

    private String username;
    private String billName;
    private String amountType; // fixed | variable
    private double amount;
    private Double estimatedAmount;
    private Double lastMonthAmount;

    private LocalDate dueDate;
    private String frequency; // one-time | weekly | monthly | yearly
    private String category;
    private String notes;

    private List<Integer> reminderDaysBefore = new ArrayList<>(); // e.g. 7,3,1,0
    private List<Integer> overdueReminderDaysAfter = new ArrayList<>(); // e.g. 1,3

    private boolean paid;
    private Double paidAmount; // cumulative amount paid toward this bill
    private LocalDateTime paidAt;
    private LocalDate snoozedUntil;

    private boolean autoGenerated;
    private String parentBillId;

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    private List<AmountHistory> amountHistory = new ArrayList<>();

    public static class AmountHistory {
        private LocalDateTime timestamp;
        private double amount;

        public AmountHistory() {}

        public AmountHistory(LocalDateTime timestamp, double amount) {
            this.timestamp = timestamp;
            this.amount = amount;
        }

        public LocalDateTime getTimestamp() { return timestamp; }
        public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }

        public double getAmount() { return amount; }
        public void setAmount(double amount) { this.amount = amount; }
    }

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getBillName() { return billName; }
    public void setBillName(String billName) { this.billName = billName; }

    public String getAmountType() { return amountType; }
    public void setAmountType(String amountType) { this.amountType = amountType; }

    public double getAmount() { return amount; }
    public void setAmount(double amount) { this.amount = amount; }

    public Double getEstimatedAmount() { return estimatedAmount; }
    public void setEstimatedAmount(Double estimatedAmount) { this.estimatedAmount = estimatedAmount; }

    public Double getLastMonthAmount() { return lastMonthAmount; }
    public void setLastMonthAmount(Double lastMonthAmount) { this.lastMonthAmount = lastMonthAmount; }

    public LocalDate getDueDate() { return dueDate; }
    public void setDueDate(LocalDate dueDate) { this.dueDate = dueDate; }

    public String getFrequency() { return frequency; }
    public void setFrequency(String frequency) { this.frequency = frequency; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }

    public List<Integer> getReminderDaysBefore() { return reminderDaysBefore; }
    public void setReminderDaysBefore(List<Integer> reminderDaysBefore) { this.reminderDaysBefore = reminderDaysBefore; }

    public List<Integer> getOverdueReminderDaysAfter() { return overdueReminderDaysAfter; }
    public void setOverdueReminderDaysAfter(List<Integer> overdueReminderDaysAfter) { this.overdueReminderDaysAfter = overdueReminderDaysAfter; }

    public boolean isPaid() { return paid; }
    public void setPaid(boolean paid) { this.paid = paid; }

    public Double getPaidAmount() { return paidAmount; }
    public void setPaidAmount(Double paidAmount) { this.paidAmount = paidAmount; }

    public LocalDateTime getPaidAt() { return paidAt; }
    public void setPaidAt(LocalDateTime paidAt) { this.paidAt = paidAt; }

    public LocalDate getSnoozedUntil() { return snoozedUntil; }
    public void setSnoozedUntil(LocalDate snoozedUntil) { this.snoozedUntil = snoozedUntil; }

    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public String getParentBillId() { return parentBillId; }
    public void setParentBillId(String parentBillId) { this.parentBillId = parentBillId; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }

    public List<AmountHistory> getAmountHistory() { return amountHistory; }
    public void setAmountHistory(List<AmountHistory> amountHistory) { this.amountHistory = amountHistory; }
}
